### ISSUE TITLE
Расширение генерирует ошибку на production сборке приложения

### ISSUE THREAD

**Issue by budarin** [lahmatiy/react-render-tracker#17]
Расширение, по всей видимости инжектирует код в приложение т.к в логах приложения видим ошибку
```
TypeError: Cannot read properties of null (reading 'forEach')\n    
at initBackend (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:14911:18)\n    
at setup (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:11628:3)\n    
at welcome (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:11574:3)
```

**Comment by lahmatiy** [comment]
Вы видите ошибку в React Devtools. RRT исполняется на клиенте, внедриться в код у него нет никакой технической возможности.

**Comment by budarin** [comment]
Понял, спасибо
